export const queryKeys = {
  runtime: ["runtime"] as const,
  summary: ["summary"] as const,
  bank: ["bank"] as const,
  bills: ["creditCardBills"] as const,
  investments: ["investments"] as const,
  investmentTransactions: ["investment-transactions"] as const,
  invoices: ["invoices"] as const,
  invoiceTransactionMappings: ["invoice-transaction-mappings"] as const,
  manualAssets: ["manualAssets"] as const,
  exchangeRates: ["exchange-rates"] as const,
  netWorthHistory: ["netWorthHistory"] as const,
  syncJobs: ["sync-jobs"] as const,
  syncSchedule: ["sync-schedule"] as const,
  notifications: ["notifications"] as const,
  classificationCategories: ["classification-categories"] as const,
  classificationRules: ["classification-rules"] as const,
  connectorSettings: (id: string) => ["connector-settings", id] as const,
  manualAssetHistory: (id: string) => ["manualAssetHistory", id] as const,
};
